# Generated by Django 5.2.6 on 2025-09-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineQuality',
            fields=[
                ('carrier_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('score_float_0_1', models.FloatField(default=0.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_json', models.JSONField()),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FareHistoryBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_iata', models.CharField(max_length=3)),
                ('destination_iata', models.CharField(max_length=3)),
                ('one_way_bool', models.BooleanField(default=True)),
                ('month_bucket', models.CharField(max_length=7)),
                ('days_to_departure_bucket', models.CharField(max_length=16)),
                ('median_price', models.FloatField(blank=True, null=True)),
                ('mean_price', models.FloatField(blank=True, null=True)),
                ('std_price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('sample_size', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['origin_iata', 'destination_iata', 'month_bucket', 'days_to_departure_bucket'], name='deals_fareh_origin__7eda87_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlightDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('search_hash', models.CharField(db_index=True, max_length=64)),
                ('deep_link', models.URLField(blank=True, null=True)),
                ('origin_iata', models.CharField(max_length=3)),
                ('destination_iata', models.CharField(max_length=3)),
                ('one_way_bool', models.BooleanField(default=True)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('return_datetime', models.DateTimeField(blank=True, null=True)),
                ('num_stops', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('layover_minutes_max', models.IntegerField(default=0)),
                ('airline_codes', models.JSONField(default=list)),
                ('cabin_class', models.CharField(blank=True, max_length=32, null=True)),
                ('price_total', models.FloatField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('num_travelers', models.IntegerField(default=1)),
                ('score_int_0_100', models.IntegerField(blank=True, null=True)),
                ('score_factors_json', models.JSONField(blank=True, null=True)),
                ('badges_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['origin_iata', 'destination_iata', 'departure_datetime', 'price_total'], name='deals_fligh_origin__953785_idx')],
            },
        ),
    ]
